# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='core.proto',
  package='singa',
  syntax='proto2',
  serialized_pb=_b('\n\ncore.proto\x12\x05singa\"p\n\x0bMemPoolConf\x12\x13\n\x04type\x18\x01 \x01(\t:\x05\x63nmem\x12\x16\n\tinit_size\x18\x02 \x01(\r:\x03\x32\x35\x36\x12\x13\n\x08max_size\x18\x03 \x01(\r:\x01\x30\x12\x0f\n\x04\x66lag\x18\x0b \x01(\r:\x01\x30\x12\x0e\n\x06\x64\x65vice\x18\x0c \x03(\r\"\xac\x01\n\x0bTensorProto\x12\r\n\x05shape\x18\x01 \x03(\r\x12\"\n\tdata_type\x18\x02 \x01(\x0e\x32\x0f.singa.DataType\x12\x0f\n\x07strides\x18\x03 \x03(\x05\x12\x16\n\nfloat_data\x18\x04 \x03(\x02\x42\x02\x10\x01\x12\x17\n\x0b\x64ouble_data\x18\x05 \x03(\x01\x42\x02\x10\x01\x12\x14\n\x08int_data\x18\x06 \x03(\x05\x42\x02\x10\x01\x12\x12\n\nbytes_data\x18\x07 \x03(\x0c*f\n\x08\x44\x61taType\x12\x0c\n\x08kFloat32\x10\x00\x12\x0c\n\x08kFloat16\x10\x01\x12\x08\n\x04kInt\x10\x02\x12\t\n\x05kChar\x10\x03\x12\x0b\n\x07kDouble\x10\x04\x12\n\n\x06kUChar\x10\x05\x12\x10\n\x0ckNumDataType\x10\x06*@\n\x08LangType\x12\x08\n\x04kCpp\x10\x00\x12\t\n\x05kCuda\x10\x01\x12\x0b\n\x07kOpencl\x10\x02\x12\x12\n\x0ekNumDeviceType\x10\x04*n\n\rCopyDirection\x12\x0f\n\x0bkHostToHost\x10\x00\x12\x11\n\rkHostToDevice\x10\x01\x12\x11\n\rkDeviceToHost\x10\x02\x12\x13\n\x0fkDeviceToDevice\x10\x03\x12\x11\n\rkNumDirection\x10\x04\x42\x18\n\x16org.apache.singa.proto')
)

_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='singa.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kFloat32', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kFloat16', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kInt', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kChar', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kDouble', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kUChar', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kNumDataType', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=310,
  serialized_end=412,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
_LANGTYPE = _descriptor.EnumDescriptor(
  name='LangType',
  full_name='singa.LangType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kCpp', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kCuda', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kOpencl', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kNumDeviceType', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=414,
  serialized_end=478,
)
_sym_db.RegisterEnumDescriptor(_LANGTYPE)

LangType = enum_type_wrapper.EnumTypeWrapper(_LANGTYPE)
_COPYDIRECTION = _descriptor.EnumDescriptor(
  name='CopyDirection',
  full_name='singa.CopyDirection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kHostToHost', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kHostToDevice', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kDeviceToHost', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kDeviceToDevice', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kNumDirection', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=480,
  serialized_end=590,
)
_sym_db.RegisterEnumDescriptor(_COPYDIRECTION)

CopyDirection = enum_type_wrapper.EnumTypeWrapper(_COPYDIRECTION)
kFloat32 = 0
kFloat16 = 1
kInt = 2
kChar = 3
kDouble = 4
kUChar = 5
kNumDataType = 6
kCpp = 0
kCuda = 1
kOpencl = 2
kNumDeviceType = 4
kHostToHost = 0
kHostToDevice = 1
kDeviceToHost = 2
kDeviceToDevice = 3
kNumDirection = 4



_MEMPOOLCONF = _descriptor.Descriptor(
  name='MemPoolConf',
  full_name='singa.MemPoolConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='singa.MemPoolConf.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("cnmem").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_size', full_name='singa.MemPoolConf.init_size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=256,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_size', full_name='singa.MemPoolConf.max_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flag', full_name='singa.MemPoolConf.flag', index=3,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device', full_name='singa.MemPoolConf.device', index=4,
      number=12, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=133,
)


_TENSORPROTO = _descriptor.Descriptor(
  name='TensorProto',
  full_name='singa.TensorProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='singa.TensorProto.shape', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='singa.TensorProto.data_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strides', full_name='singa.TensorProto.strides', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_data', full_name='singa.TensorProto.float_data', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='double_data', full_name='singa.TensorProto.double_data', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='int_data', full_name='singa.TensorProto.int_data', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='bytes_data', full_name='singa.TensorProto.bytes_data', index=6,
      number=7, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=308,
)

_TENSORPROTO.fields_by_name['data_type'].enum_type = _DATATYPE
DESCRIPTOR.message_types_by_name['MemPoolConf'] = _MEMPOOLCONF
DESCRIPTOR.message_types_by_name['TensorProto'] = _TENSORPROTO
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE
DESCRIPTOR.enum_types_by_name['LangType'] = _LANGTYPE
DESCRIPTOR.enum_types_by_name['CopyDirection'] = _COPYDIRECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemPoolConf = _reflection.GeneratedProtocolMessageType('MemPoolConf', (_message.Message,), dict(
  DESCRIPTOR = _MEMPOOLCONF,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:singa.MemPoolConf)
  ))
_sym_db.RegisterMessage(MemPoolConf)

TensorProto = _reflection.GeneratedProtocolMessageType('TensorProto', (_message.Message,), dict(
  DESCRIPTOR = _TENSORPROTO,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:singa.TensorProto)
  ))
_sym_db.RegisterMessage(TensorProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026org.apache.singa.proto'))
_TENSORPROTO.fields_by_name['float_data'].has_options = True
_TENSORPROTO.fields_by_name['float_data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_TENSORPROTO.fields_by_name['double_data'].has_options = True
_TENSORPROTO.fields_by_name['double_data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_TENSORPROTO.fields_by_name['int_data'].has_options = True
_TENSORPROTO.fields_by_name['int_data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
